laravel-workflow/laravel-workflow

- README.md
- composer.json
- src/Activity.php
- src/Models/StoredWorkflow.php
- src/Models/StoredWorkflowSignal.php
- src/Signal.php
- src/SignalMethod.php
- src/Workflow.php
- src/WorkflowStub.php
- src/migrations/2022_01_01_000002_create_workflow_signals_table.php
- tests/Feature/WorkflowTest.php
- tests/TestSimpleWorkflow.php
- tests/TestWorkflow.php
This PR adds the ability to await on a condition and signal a workflow.
For example:
```
class TestWorkflow extends Workflow
{
private bool $canceled = false;
#[SignalMethod]
public function cancel()
{
$this->canceled = true;
}
public function execute()
{
yield WorkflowStub::await(fn () => $this->canceled);
return;
}
}
```
This workflow will reach the `await()` call and then pause until some external code signals the workflow like this:
```
$workflow->cancel();
```
> Add signals

- README.md
- src/Models/StoredWorkflow.php
- src/Models/StoredWorkflowTimer.php
- src/Workflow.php
- src/WorkflowStub.php
- src/migrations/2022_01_01_000003_create_workflow_timers_table.php
- tests/Feature/TimerWorkflowTest.php
- tests/Feature/WorkflowTest.php
- tests/Fixtures/TestActivity.php
- tests/Fixtures/TestFailingActivity.php
- tests/Fixtures/TestOtherActivity.php
- tests/Fixtures/TestSimpleWorkflow.php
- tests/Fixtures/TestTimerWorkflow.php
- tests/Fixtures/TestWorkflow.php
- tests/TestCase.php
This PR adds the ability to create a timer and allow a workflow to pause execution for a fixed amount of time. This uses [delayed dispatching](https://laravel.com/docs/9.x/queues#delayed-dispatching) under the hood. Therefore, there is nothing actually running while a timer is active.
For example the following workflow will pause for 5 minutes and then complete:
```
class TestWorkflow extends Workflow
{
public function execute()
{
yield WorkflowStub::timer(300);
return;
}
}
```
I will eventually make these timers cancelable.
> Add timers

- src/Workflow.php
- src/WorkflowStub.php
- tests/Feature/AwaitWithTimeoutWorkflowTest.php
- tests/Fixtures/TestAwaitWithTimeoutWorkflow.php
This PR adds the ability to await on a signal or the completion of a timer. If the timer completes first then `yield WorkflowStub::awaitWithTimeout()` returns `false` otherwise it returns `true`.
> Add awaitWithTimeout

- src/Activity.php
- src/Middleware/WorkflowMiddleware.php
- src/States/WorkflowStatus.php
- src/Workflow.php
- tests/Feature/AwaitWithTimeoutWorkflowTest.php
- tests/Feature/AwaitWorkflowTest.php
- tests/Feature/ExceptionWorkflowTest.php
- tests/Feature/FailingWorkflowTest.php
- tests/Feature/WorkflowTest.php
- tests/Fixtures/TestAwaitWorkflow.php
- tests/Fixtures/TestExceptionActivity.php
- tests/Fixtures/TestExceptionWorkflow.php
- tests/Fixtures/TestFailingWorkflow.php
- tests/Fixtures/TestWorkflow.php
This PR updates the default workflow and activity retry policies. It also sets a backoff policy for activities. Workflows are now only tried once and activities are retried forever. This allows for the pattern of a failing activity to continue to be retried until it is fixed via either some transient condition resolving itself or via a manual intervention such as a code deploy or database change. The tests have also been refactored for some cleanup and readability.
> Add backoff

- src/Activity.php
- tests/Feature/HeartbeatWorkflowTest.php
- tests/Fixtures/TestHeartbeatActivity.php
- tests/Fixtures/TestHeartbeatWorkflow.php
This PR adds the ability to heartbeat an activity so that it doesn't get killed for being frozen.
```
class TestHeartbeatActivity extends Activity
{
public $timeout = 5;
public function execute()
{
for ($i = 0; $i < 10; $i++) { 
sleep(1);
$this->heartbeat();
}
return 'activity';
}
}
```
> Add heartbeats

- src/Middleware/WorkflowMiddleware.php
- src/Models/StoredWorkflow.php
- src/Models/StoredWorkflowLog.php
- src/Models/StoredWorkflowSignal.php
- src/Models/StoredWorkflowTimer.php
- src/Workflow.php
- src/WorkflowStub.php
- src/migrations/2022_01_01_000000_create_workflows_table.php
- src/migrations/2022_01_01_000001_create_workflow_logs_table.php
- src/migrations/2022_01_01_000002_create_workflow_signals_table.php
- src/migrations/2022_01_01_000003_create_workflow_timers_table.php
- tests/Feature/WorkflowTest.php
By default, Laravel timestamps only have second precision. This PR changes them to microseconds for the stored workflows. Migration updates will be done in place until this is at least out of alpha.
> Microsecond timestamps

- src/migrations/2022_01_01_000000_create_workflows_table.php
Adds an index for the status column. This isn't needed for the package itself but the Waterline UI will need it.
> Index status

- src/Activity.php
- src/ActivityStub.php
- src/Middleware/WithoutOverlappingMiddleware.php
- src/Signal.php
- src/Workflow.php
- src/WorkflowStub.php
- tests/Feature/ConcurrentWorkflowTest.php
- tests/Fixtures/TestConcurrentWorkflow.php
This PR adds a new middleware that was partially written by ChatGPT. The built-in Laravel middleware `WithoutOverlapping` wouldn't support the ability for parallel activities so I wrote one with the help of ChatGPT.
Here's an example of how you would use it:
```
$promise1 = ActivityStub::make(MyActivity::class);
$promise2 = ActivityStub::make(MyActivity::class);
yield ActivityStub::all([$promise1, $promise2]);
```
This is still a work in progress...
> Add parallel activities

- src/Models/StoredWorkflow.php
- src/Models/StoredWorkflowException.php
- src/Models/StoredWorkflowLog.php
- src/Models/StoredWorkflowSignal.php
- src/Models/StoredWorkflowTimer.php
- src/Providers/WorkflowServiceProvider.php
- src/WorkflowStub.php
- src/config/workflows.php
This pull request updates the `StoredWorkflow`, `StoredWorkflowException`, `StoredWorkflowLog`, and `StoredWorkflowSignal` classes to use the values returned by `config('workflows.stored_workflow_model')`, `config('workflows.stored_workflow_exception_model')`, `config('workflows.stored_workflow_log_model')`, and `config('workflows.stored_workflow_signal_model')`, respectively, rather than hardcoding the class names. This allows developers to specify their own custom classes that extend these classes and customize their behavior. The main reason would be to customize the `$connection` options.
> Use config to specify stored workflow models

- src/Signal.php
> Use config queue

- src/Traits/Sagas.php
Compensating activities should be run in reverse of the order they were added.
> Reverse compensations

- src/Models/StoredWorkflow.php
- src/config/workflows.php
Added an override to allow setting the relationship table name in the configuration. This allows the ability to modify the database structure during migrations and still maintain the table structure itself.
> Allow relationship table name override

- composer.json
This pull request makes it possible to use react/promise 3.
Please check the [release  announcement](https://clue.engineering/2023/announcing-reactphp-promise-v3) and [change-log](https://github.com/reactphp/promise/releases/tag/v3.0.0).
I have done this and looked through the [laravel-workflow](https://github.com/laravel-workflow/laravel-workflow) source-code to check if any of the deprecated or changed functionality was used, but it looks like it didn't.
That is why I made the upgrade optional.
I have -hand-tested it with my workflows and everything works like a charm.
> React promise 3

- src/Events/WorkflowFailed.php
- src/Listeners/MonitorWorkflowFailed.php
- src/Workflow.php
- src/WorkflowStub.php
- tests/Unit/Commands/ActivityMakeCommandTest.php
- tests/Unit/Commands/WorkflowMakeCommandTest.php
- tests/Unit/Listeners/MonitorActivityCompletedTest.php
- tests/Unit/Listeners/MonitorActivityFailedTest.php
- tests/Unit/Listeners/MonitorActivityStartedTest.php
- tests/Unit/Listeners/MonitorWorkflowCompletedTest.php
- tests/Unit/Listeners/MonitorWorkflowFailedTest.php
- tests/Unit/Listeners/MonitorWorkflowStartedTest.php
Don't emit the exception on a failed workflow event. It is always the same value of 'Workflow failed.' and therefore isn't useful.
> Don't emit exception

- src/Activity.php
- src/Events/WorkflowFailed.php
- src/Listeners/MonitorWorkflowFailed.php
- src/WorkflowStub.php
- tests/Unit/Listeners/MonitorWorkflowFailedTest.php
In some cases the exception is useful, such as when the exception occurs inside the workflow rather than an activity.
> Emit exception

- src/WorkflowStub.php
- tests/Fixtures/TestBadConnectionWorkflow.php
- tests/Unit/WorkflowStubTest.php
This PR fixes the bug that leads to using a wrong queue and connection with multiple workflows
```
$workflow1 = WorkflowStub::make(MyWorkflow::class);
$workflow2 = WorkflowStub::make(MyWorkflow2::class); // <- This workflow overwrites static context
$workflow1->start();
$workflow2->start();
$workflow1->setTestString('string 1'); // <- this signal uses connection and queue from workflow 2 because it uses info from the context that was overwritten. This PR fixes it
$workflow2->setTestString('string 2');
```
> Should use a storedWorkflow from the class property instead of the static context

- src/Models/StoredWorkflow.php
The relations 'logs', 'signals', 'timers' and 'exceptions' were sometimes returned out-of-order
Waterline displays these relations without reordering them as well, which in turn would show incorrect information about their order of execution and their time
> Set default order for workflow relations

- src/Workflow.php
When something is broken with Workflow, we sometimes receive just 'Workflow failed' in logs/failed jobs, without any future explanations. That will pass also information about previous exception, which was cause of that issue
> feat: passing previous exception to exception thrown from workflow

- src/Activity.php
- src/Exceptions/NonRetryableException.php
- src/Exceptions/NonRetryableExceptionContract.php
- tests/Feature/ExceptionWorkflowTest.php
- tests/Fixtures/NonRetryableTestExceptionActivity.php
- tests/Fixtures/NonRetryableTestExceptionWorkflow.php
The PR adds NonRetryableException.
When this exception is thrown, The Activity will not retry and The Workflow Marks as Fail.
This implementation will work similarly to Cloudflare Workflow NonRetryableError
[NonRetryableException](https://developers.cloudflare.com/workflows/build/sleeping-and-retrying/#force-a-workflow-to-fail)
> Added NonRetryableException

- src/Activity.php
- src/ActivityStub.php
- src/ChildWorkflowStub.php
- src/Serializers/AbstractSerializer.php
- src/Serializers/Base64.php
- src/Serializers/Serializer.php
- src/Serializers/Y.php
- src/Traits/AwaitWithTimeouts.php
- src/Traits/Awaits.php
- src/Traits/SideEffects.php
- src/Traits/Timers.php
- src/Workflow.php
- src/WorkflowStub.php
- src/config/workflows.php
- tests/Feature/Base64WorkflowTest.php
- tests/Feature/ExceptionWorkflowTest.php
- tests/Unit/ActivityStubTest.php
- tests/Unit/ActivityTest.php
- tests/Unit/ChildWorkflowStubTest.php
- tests/Unit/Serializers/EncodeTest.php
- tests/Unit/Serializers/SerializeTest.php
- tests/Unit/Traits/AwaitWithTimeoutsTest.php
- tests/Unit/Traits/AwaitsTest.php
- tests/Unit/Traits/SideEffectsTest.php
- tests/Unit/Traits/TimersTest.php
- tests/Unit/WorkflowStubTest.php
- tests/Unit/WorkflowTest.php
This change allows you to optionally use the base64 serializer instead of Y. The tradeoff is between speed and size. Base64 is faster but adds more overhead. Y is slower but smaller. It defaults to Y to avoid introducing breaking changes. This also assumes you are starting from scratch as switching from Y to Base64 or vice versa once you have generated some workflows is not supported and beyond the scope of this PR.
> Add base64 serializer (#196)

- tests/TestCase.php
Removed the call to 'queue:failed-table' from the test case.
> Remove queue:failed-table call from TestCase
