laravel-workflow/laravel-workflow

- src/Activity.php
- src/Models/StoredWorkflow.php
- src/Models/StoredWorkflowException.php
- src/WorkflowStub.php
- src/migrations/2022_01_01_000004_create_workflow_exceptions_table.php
- tests/Feature/ExceptionWorkflowTest.php
This will be useful later so that Waterline and CLI tools can easily debug failing workflows.
> Log exceptions

- src/Activity.php
This PR adds a helper method so that users won't have to reference the model property directly.
> Add workflowId

- src/Activity.php
- src/Signal.php
- src/Workflow.php
This PR adds the microsecond portion of the current log timestamp otherwise it will miss some signals if they are sent very quickly.
> Fix signal timings

- src/QueryMethod.php
- src/Workflow.php
- src/WorkflowStub.php
- tests/Feature/WorkflowTest.php
- tests/Fixtures/TestWorkflow.php
These changes allow workflows to be queried from external code and to be replayed without modifying their state.
> Add Queries

- composer.json
- src/Serializers/SerializerInterface.php
- src/Serializers/Y.php
This adds the excellent https://github.com/opis/closure library to add some better compatibility plus cryptographic signatures when serializing/unserializing exceptions.
> Add Serializable Closures

- phpunit.xml
- tests/Feature/AwaitWithTimeoutWorkflowTest.php
- tests/Feature/TimerWorkflowTest.php
- tests/Unit/EncodeTest.php
- tests/Unit/SerializeTest.php
> Unit Tests

- src/WorkflowStub.php
- tests/Fixtures/TestWorkflow.php
- tests/Unit/WorkflowStubTest.php
> Fix Already Logged Activities

- src/ActivityStub.php
- src/Traits/AwaitWithTimeouts.php
- src/Traits/Awaits.php
- src/Traits/SideEffects.php
- src/Traits/Timers.php
- src/WorkflowStub.php
- tests/Feature/SideEffectWorkflowTest.php
- tests/Fixtures/TestSideEffectWorkflow.php
- tests/Unit/ActivityStubTest.php
- tests/Unit/Traits/AwaitWithTimeoutsTest.php
- tests/Unit/Traits/AwaitsTest.php
- tests/Unit/Traits/SideEffectsTest.php
- tests/Unit/Traits/TimersTest.php
- tests/Unit/WorkflowStubTest.php
Adds Side Effect feature:
- non-deterministic code executes only once and stores result
- future executions return stored result
> Side Effects

- composer.json
- src/Activity.php
- src/Serializers/Y.php
- tests/Fixtures/TestEnum.php
- tests/Unit/ActivityStubTest.php
- tests/Unit/ActivityTest.php
- tests/Unit/Serializers/SerializeTest.php
- tests/Unit/Traits/AwaitWithTimeoutsTest.php
- tests/Unit/Traits/AwaitsTest.php
- tests/Unit/Traits/SideEffectsTest.php
- tests/Unit/Traits/TimersTest.php
- tests/Unit/WorkflowStubTest.php
> Use laravel/serializable-closure

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/docker/app/Dockerfile
- src/Serializers/Y.php
- tests/Feature/ExceptionWorkflowTest.php
- tests/Unit/Serializers/SerializeTest.php
> Fix Closure Error

- src/ChildWorkflowStub.php
- src/Models/StoredWorkflow.php
- src/WorkflowStub.php
- tests/Feature/ParentWorkflowTest.php
- tests/Fixtures/TestChildExceptionWorkflow.php
- tests/Fixtures/TestParentExceptionWorkflow.php
- tests/Unit/ChildWorkflowStubTest.php
- tests/Unit/WorkflowStubTest.php
> Restart Child Workflows

- src/Signal.php
- src/Traits/Timers.php
- src/Workflow.php
- src/WorkflowStub.php
- tests/Feature/ParentWorkflowTest.php
- tests/Fixtures/TestChildTimerWorkflow.php
- tests/Fixtures/TestParentTimerWorkflow.php
- tests/Unit/WorkflowStubTest.php
> Convert string to Carbon

- src/Providers/WorkflowServiceProvider.php
- src/Serializers/Y.php
> Fix serialization

- src/Middleware/WorkflowMiddleware.php
> Set inactive after job

- src/Commands/ActivityMakeCommand.php
- src/Commands/WorkflowMakeCommand.php
- src/Commands/stubs/activity.stub
- src/Commands/stubs/workflow.stub
- src/Providers/WorkflowServiceProvider.php
- src/config/workflows.php
- tests/Unit/Commands/ActivityMakeCommandTest.php
- tests/Unit/Commands/WorkflowMakeCommandTest.php
Adds make commands for workflows and activities.
```
php artisan make:workflow MyWorkflow
php artisan make:activity MyActivity
```
Defaults to `App\Workflows\` but can be changed with `workflows_folder` configuration setting.
> Add make commands

- src/Serializers/Y.php
This uses Laravel's `SerializesAndRestoresModelIdentifiers` trait to transform models into model identifiers, which will take up less space in the database (at the cost of extra queries).
> Serialize models

- src/migrations/2022_01_01_000001_create_workflow_logs_table.php
- src/migrations/2022_01_01_000002_create_workflow_signals_table.php
- src/migrations/2022_01_01_000003_create_workflow_timers_table.php
- src/migrations/2022_01_01_000004_create_workflow_exceptions_table.php
- src/migrations/2022_01_01_000005_create_workflow_relationships_table.php
We need the same precision on all timestamps.
> Fix timestamps

- src/Workflow.php
> Use activity middleware

- src/Activity.php
- src/AsyncWorkflow.php
- src/Workflow.php
- tests/Fixtures/TestActivity.php
- tests/Fixtures/TestAsyncWorkflow.php
- tests/Fixtures/TestOtherActivity.php
- tests/Fixtures/TestWorkflow.php
@EgorGruzdev I have copied your idea from #124 but I am using the trait directly. I have also added support for both Workflow and Activity execute method. If you could please test this out and tell me what you think that would be great!
> Resolve dependencies using container

- src/Events/ActivityCompleted.php
- src/Events/ActivityFailed.php
- src/Events/ActivityStarted.php
- src/Events/WorkflowCompleted.php
- src/Events/WorkflowFailed.php
- src/Events/WorkflowStarted.php
- src/Listeners/MonitorActivityCompleted.php
- src/Listeners/MonitorActivityFailed.php
- src/Listeners/MonitorActivityStarted.php
- src/Listeners/MonitorWorkflowCompleted.php
- src/Listeners/MonitorWorkflowFailed.php
- src/Listeners/MonitorWorkflowStarted.php
- src/Middleware/WorkflowMiddleware.php
- src/Providers/WorkflowServiceProvider.php
- src/Traits/FetchesMonitorAuth.php
- src/Workflow.php
- src/WorkflowStub.php
- src/config/workflows.php
- tests/Unit/Listeners/MonitorActivityCompletedTest.php
- tests/Unit/Listeners/MonitorActivityFailedTest.php
- tests/Unit/Listeners/MonitorActivityStartedTest.php
- tests/Unit/Listeners/MonitorWorkflowCompletedTest.php
- tests/Unit/Listeners/MonitorWorkflowFailedTest.php
- tests/Unit/Listeners/MonitorWorkflowStartedTest.php
- tests/Unit/Middleware/WorkflowMiddlewareTest.php
This PR adds common events and the ability to monitor workflow/activity lifecycle events with a remote API.
> Add events

- src/Traits/FetchesMonitorAuth.php
This should be 1 hour (3600 seconds).
> Set cache time

- src/Activity.php
- src/Middleware/WithoutOverlappingMiddleware.php
- src/Workflow.php
- tests/Unit/Middleware/WithoutOverlappingMiddlewareTest.php
Instead of counting the activities, store an id for each in an array and then give them an individual TTL.
> Restart if killed

- src/Events/ActivityStarted.php
- src/Events/WorkflowCompleted.php
- src/Events/WorkflowFailed.php
- src/Events/WorkflowStarted.php
PR allows to use uuid/ulid/wherever string ids for models
> Allow string ids

- src/Activity.php
- src/Workflow.php
- tests/Feature/DispatchWorkflowInTransactionTest.php
- tests/Fixtures/TestSimpleWorkflow.php
> Fix race condition

- src/Events/ActivityCompleted.php
- src/Events/ActivityFailed.php
- src/Middleware/WorkflowMiddleware.php
- tests/Unit/Listeners/MonitorActivityCompletedTest.php
- tests/Unit/Listeners/MonitorActivityFailedTest.php
> Added workflowId to ActivityCompleted and ActivityFailed

- src/Middleware/WithoutOverlappingMiddleware.php
- src/Middleware/WorkflowMiddleware.php
- tests/Feature/TimeoutWorkflowTest.php
> Remove unused code

- src/Serializers/Serializer.php
- tests/Feature/Base64WorkflowTest.php
- tests/Unit/Serializers/EncodeTest.php
- tests/Unit/Serializers/SerializeTest.php
> Fix config name
